name: test-curl
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch: {}
jobs:
  tick:
    runs-on: ubuntu-latest
    steps:
      - name: process-publish-jobs
        run: curl -sf -X GET "https://lunaads.vercel.app/api/cron/process-publish-jobs" -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}"
